# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Event',
        ),
    ]
