# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180328_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='text',
            new_name='event_info',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
