# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180329_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rocksoc_event',
            field=models.BooleanField(default=False),
        ),
    ]
