# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_event_rocksoc_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='rocksoc_event',
            new_name='rockSoc_event',
        ),
    ]
