# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180331_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_to_Facebook_event',
            field=models.TextField(blank=True, null=True),
        ),
    ]
