# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-19 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_event_wus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='wus',
            new_name='WUS',
        ),
    ]
