# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20180419_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
