# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-30 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20180424_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
