# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-18 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
