# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-18 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20180918_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_caption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
