# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20180920_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('data', models.ImageField(upload_to='images')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.ManyToManyField(blank=True, to='pages.Tag'),
        ),
        migrations.AddField(
            model_name='album',
            name='highlight',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_highlight', to='pages.Image'),
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, to='pages.Image'),
        ),
    ]
