# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20180921_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='rule',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='pages.Rule'),
        ),
    ]
