# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-29 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_auto_20180922_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
