# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_auto_20181007_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_category_name', models.CharField(max_length=200)),
            ],
        ),
    ]
