# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-07 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_auto_20181007_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.Album_Category'),
        ),
    ]
